float:
  any:
  - base_args: ['@metric']
    constructor: MySQL
    disabled: false
    docker_tag: ann-benchmarks-mysql
    module: ann_benchmarks.algorithms.mysql
    name: mysql-nq
    run_groups:
      base:
        arg_groups: [{}]
        args: {}
        query_args: [[1], [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]]
  - base_args: ['@metric']
    constructor: MySQL
    disabled: false
    docker_tag: ann-benchmarks-mysql
    module: ann_benchmarks.algorithms.mysql
    name: mysql-pq49
    run_groups:
      base:
        arg_groups: [{pq: 49}]
        args: {}
        query_args: [[1, 2, 4, 8, 16, 32], [16, 32, 64, 128, 256]]
  - base_args: ['@metric']
    constructor: MySQL
    disabled: false
    docker_tag: ann-benchmarks-mysql
    module: ann_benchmarks.algorithms.mysql
    name: mysql-pq98
    run_groups:
      base:
        arg_groups: [{pq: 98}]
        args: {}
        query_args: [[1, 2, 4, 8], [16, 32, 64, 128, 256]]
  - base_args: ['@metric']
    constructor: MySQL
    disabled: false
    docker_tag: ann-benchmarks-mysql
    module: ann_benchmarks.algorithms.mysql
    name: mysql-pq196
    run_groups:
      base:
        arg_groups: [{pq: 196}]
        args: {}
        query_args: [[1.0, 1.5, 2.0, 2.5, 3.0], [16, 32, 64, 128, 256]]
  - base_args: ['@metric']
    constructor: MySQL
    disabled: false
    docker_tag: ann-benchmarks-mysql
    module: ann_benchmarks.algorithms.mysql
    name: mysql-fq-float16
    run_groups:
      base:
        arg_groups: [{fq: "float16"}]
        args: {}
        query_args: [[1], [16, 32, 64, 128, 256, 512, 1024, 2048, 4096]]
  - base_args: ['@metric']
    constructor: MySQL
    disabled: false
    docker_tag: ann-benchmarks-mysql
    module: ann_benchmarks.algorithms.mysql
    name: mysql-fq-onebit
    run_groups:
      base:
        arg_groups: [{fq: "onebit"}]
        args: {}
        query_args: [[1, 2, 4, 8, 16, 32], [16, 32, 64, 128, 256]]
